// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entry/otp/otp_pb/otp.proto

package otp_pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GenerateRequest) Validate() error {
	return nil
}
func (this *GenerateResponse) Validate() error {
	return nil
}
func (this *ValidateRequest) Validate() error {
	return nil
}
func (this *ValidateResponse) Validate() error {
	return nil
}
