// Code generated by protoc-gen-lava. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc         v3.17.3
// source: entry/otp/otp_pb/otp.proto

package otp_pb

import (
	gin "github.com/gin-gonic/gin"
	grpcc "github.com/pubgo/lava/clients/grpcc"
	xgen "github.com/pubgo/lava/xgen"
	xerror "github.com/pubgo/xerror"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func GetOtpClient(srv string, opts ...func(cfg *grpcc.Cfg)) OtpClient {
	return &otpClient{grpcc.GetClient(srv, opts...)}
}
func init() {
	var mthList []xgen.GrpcRestHandler
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &GenerateRequest{},
		Output:       &GenerateResponse{},
		Service:      "otp.Otp",
		Name:         "Generate",
		Method:       "POST",
		Path:         "/otp/otp/generate",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: false,
	})
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &ValidateRequest{},
		Output:       &ValidateResponse{},
		Service:      "otp.Otp",
		Name:         "Validate",
		Method:       "POST",
		Path:         "/otp/otp/validate",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: false,
	})
	xgen.Add(RegisterOtpServer, mthList)
	xgen.Add(RegisterOtpHandler, nil)
	xgen.Add(RegisterOtpGinServer, nil)
}
func RegisterOtpGinServer(r gin.IRouter, server OtpServer) {
	xerror.Assert(r == nil || server == nil, "router or server is nil")
	r.Handle("POST", "/otp/otp/generate", func(ctx *gin.Context) {
		var req = new(GenerateRequest)
		xerror.Panic(ctx.ShouldBindJSON(req))
		var resp, err = server.Generate(ctx, req)
		xerror.Panic(err)
		ctx.JSON(200, resp)
	})
	r.Handle("POST", "/otp/otp/validate", func(ctx *gin.Context) {
		var req = new(ValidateRequest)
		xerror.Panic(ctx.ShouldBindJSON(req))
		var resp, err = server.Validate(ctx, req)
		xerror.Panic(err)
		ctx.JSON(200, resp)
	})
}
