// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entry/user/user_pb/user.proto

package user_pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Account) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Session) Validate() error {
	return nil
}
func (this *CreateRequest) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *CreateResponse) Validate() error {
	if this.Account != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Account); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Account", err)
		}
	}
	return nil
}
func (this *DeleteRequest) Validate() error {
	return nil
}
func (this *DeleteResponse) Validate() error {
	return nil
}
func (this *ReadRequest) Validate() error {
	return nil
}
func (this *ReadResponse) Validate() error {
	if this.Account != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Account); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Account", err)
		}
	}
	return nil
}
func (this *UpdateRequest) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *UpdateResponse) Validate() error {
	return nil
}
func (this *UpdatePasswordRequest) Validate() error {
	return nil
}
func (this *UpdatePasswordResponse) Validate() error {
	return nil
}
func (this *ReadSessionRequest) Validate() error {
	return nil
}
func (this *ReadSessionResponse) Validate() error {
	if this.Session != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Session); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Session", err)
		}
	}
	return nil
}
func (this *LoginRequest) Validate() error {
	return nil
}
func (this *LoginResponse) Validate() error {
	if this.Session != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Session); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Session", err)
		}
	}
	return nil
}
func (this *LogoutRequest) Validate() error {
	return nil
}
func (this *LogoutResponse) Validate() error {
	return nil
}
func (this *VerifyEmailRequest) Validate() error {
	return nil
}
func (this *VerifyEmailResponse) Validate() error {
	return nil
}
func (this *SendVerificationEmailRequest) Validate() error {
	return nil
}
func (this *SendVerificationEmailResponse) Validate() error {
	return nil
}
func (this *SendPasswordResetEmailRequest) Validate() error {
	return nil
}
func (this *SendPasswordResetEmailResponse) Validate() error {
	return nil
}
func (this *ResetPasswordRequest) Validate() error {
	return nil
}
func (this *ResetPasswordResponse) Validate() error {
	return nil
}
func (this *ListRequest) Validate() error {
	return nil
}
func (this *ListResponse) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
